server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: fetching-tickets-service
          uri: http://localhost:8081
          predicates:
            - Path=api/v1/tickets/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
