server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: auth-service
          uri: lb://AUTHENTIFICATION
          predicates:
            - Path=/auth/**

        - id: config-service
          uri: lb://CONFIGSERVICE
          predicates:
            - Path=/config/**

        - id: discovery-service
          uri: lb://DISCOVERYSERVICE
          predicates:
            - Path=/discovery/**

        - id: fetching-tickets
          uri: lb://FETCHINGTICKETS
          predicates:
            - Path=/tickets/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
